/**
 * Syncs the version from package.json to:
 * - Frontend: version.ts
 * - Backend: Dishhive.Api.csproj and AppVersion.cs
 * This ensures all parts of the application share the same version
 * (see docs/VERSION_MANAGEMENT.md in Freezy for the ecosystem convention)
 */
const fs = require('fs');
const path = require('path');

// Paths
const packageJsonPath = path.join(__dirname, '..', 'package.json');
const versionTsPath = path.join(__dirname, '..', 'src', 'environments', 'version.ts');
const backendCsprojPath = path.join(__dirname, '..', '..', 'Dishhive.Api', 'Dishhive.Api.csproj');
const backendVersionPath = path.join(__dirname, '..', '..', 'Dishhive.Api', 'AppVersion.cs');

// Read package.json
const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
const version = packageJson.version;

console.log(`Syncing version ${version}...`);

// ============================================================================
// Frontend: Create/update version.ts
// ============================================================================
const versionTs = `// This file is auto-generated by scripts/sync-version.js
// Do not edit manually - changes will be overwritten
export const VERSION = '${version}';
`;
fs.writeFileSync(versionTsPath, versionTs, 'utf8');
console.log(`✓ Generated version.ts`);

// ============================================================================
// Backend: Update .csproj file (skipped when the backend is not present,
// e.g. inside the frontend-only Docker build stage)
// ============================================================================
if (fs.existsSync(backendCsprojPath)) {
  let csprojContent = fs.readFileSync(backendCsprojPath, 'utf8');

  csprojContent = csprojContent
    .replace(/<Version>.*?<\/Version>/, `<Version>${version}</Version>`)
    .replace(/<AssemblyVersion>.*?<\/AssemblyVersion>/, `<AssemblyVersion>${version}</AssemblyVersion>`)
    .replace(/<FileVersion>.*?<\/FileVersion>/, `<FileVersion>${version}</FileVersion>`);

  fs.writeFileSync(backendCsprojPath, csprojContent, 'utf8');
  console.log(`✓ Updated Dishhive.Api.csproj`);

  const backendVersionCs = `// This file is auto-generated by ../dishhive-web/scripts/sync-version.js
// Do not edit manually - changes will be overwritten

/// <summary>
/// Contains the application version synchronized from package.json
/// </summary>
public static class AppVersion
{
    /// <summary>
    /// Current application version
    /// </summary>
    public const string Version = "${version}";
}
`;
  fs.writeFileSync(backendVersionPath, backendVersionCs, 'utf8');
  console.log(`✓ Generated AppVersion.cs`);
} else {
  console.warn(`⚠ Backend .csproj not found at ${backendCsprojPath} (frontend-only build)`);
}

console.log(`\n✅ Version ${version} synced`);
