#!/usr/bin/env node
/**
 * sync-version.js
 * Reads version from package.json and syncs it to:
 * - AppVersion.cs (.NET)
 * - Dishhive.Api.csproj (assembly version)
 * - src/environments/version.ts (frontend)
 *
 * Run: node scripts/sync-version.js
 * Called automatically by: npm run build
 */

const fs = require('fs');
const path = require('path');

const rootDir = path.join(__dirname, '..');
const packageJson = JSON.parse(fs.readFileSync(path.join(rootDir, 'package.json'), 'utf8'));
const version = packageJson.version;

console.log(`Syncing version: ${version}`);

// --- Frontend: generate version.ts ---
const versionTsPath = path.join(rootDir, 'src', 'environments', 'version.ts');
const versionTs = `// Auto-generated by scripts/sync-version.js — DO NOT EDIT MANUALLY\nexport const APP_VERSION = '${version}';\n`;
fs.writeFileSync(versionTsPath, versionTs);
console.log(`  Updated: ${versionTsPath}`);

// --- Backend: update AppVersion.cs ---
const appVersionPath = path.join(rootDir, '..', 'Dishhive.Api', 'AppVersion.cs');
if (fs.existsSync(appVersionPath)) {
  const appVersionCs = `// Auto-generated by scripts/sync-version.js — DO NOT EDIT MANUALLY\nnamespace Dishhive.Api;\n\npublic static class AppVersion\n{\n    public const string Version = "${version}";\n}\n`;
  fs.writeFileSync(appVersionPath, appVersionCs);
  console.log(`  Updated: ${appVersionPath}`);
} else {
  console.warn(`  Skipped AppVersion.cs — file not found at: ${appVersionPath}`);
}

// --- Backend: update .csproj version ---
const csprojPath = path.join(rootDir, '..', 'Dishhive.Api', 'Dishhive.Api.csproj');
if (fs.existsSync(csprojPath)) {
  let csproj = fs.readFileSync(csprojPath, 'utf8');
  csproj = csproj.replace(/<Version>.*?<\/Version>/, `<Version>${version}</Version>`);
  csproj = csproj.replace(/<AssemblyVersion>.*?<\/AssemblyVersion>/, `<AssemblyVersion>${version}</AssemblyVersion>`);
  csproj = csproj.replace(/<FileVersion>.*?<\/FileVersion>/, `<FileVersion>${version}</FileVersion>`);
  fs.writeFileSync(csprojPath, csproj);
  console.log(`  Updated: ${csprojPath}`);
} else {
  console.warn(`  Skipped .csproj — file not found at: ${csprojPath}`);
}

console.log('Version sync complete.');
