// <auto-generated />
using System;
using Dishhive.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dishhive.Api.Data.Migrations
{
    [DbContext(typeof(DishhiveDbContext))]
    [Migration("20260711223048_AddAiPlanningRunMetrics")]
    partial class AddAiPlanningRunMetrics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dishhive.Api.Models.AiModelTestRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ChecksJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("ElapsedMs")
                        .HasColumnType("bigint");

                    b.Property<bool>("EndpointReachable")
                        .HasColumnType("boolean");

                    b.Property<bool?>("EvaluationPassed")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool?>("ModelListed")
                        .HasColumnType("boolean");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ResponseMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("TestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("TokensPerSecond")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ConfigKey")
                        .IsUnique();

                    b.ToTable("AiModelTestRecords");
                });

            modelBuilder.Entity("Dishhive.Api.Models.AiPlanningRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("CapabilityWaitMs")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CompletionAttempts")
                        .HasColumnType("integer");

                    b.Property<long>("CompletionDurationMs")
                        .HasColumnType("bigint");

                    b.Property<int>("EmptySearchCount")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ExternalSuggestions")
                        .HasColumnType("integer");

                    b.Property<int>("FallbackSuggestions")
                        .HasColumnType("integer");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("Instructions")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ModelTurns")
                        .HasColumnType("integer");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<int>("ParseFailures")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("ReasoningTokens")
                        .HasColumnType("bigint");

                    b.Property<int>("RecipeResolutionCount")
                        .HasColumnType("integer");

                    b.Property<long>("RecipeResolutionDurationMs")
                        .HasColumnType("bigint");

                    b.Property<int>("RecipeResolutionFailureCount")
                        .HasColumnType("integer");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("RequestedDays")
                        .HasColumnType("integer");

                    b.Property<int>("ResearchCalls")
                        .HasColumnType("integer");

                    b.Property<int>("SearchCount")
                        .HasColumnType("integer");

                    b.Property<long>("SearchDurationMs")
                        .HasColumnType("bigint");

                    b.Property<int>("SearchResultCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SuggestedItems")
                        .HasColumnType("integer");

                    b.Property<long>("TotalDurationMs")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalTokens")
                        .HasColumnType("bigint");

                    b.Property<bool>("UsedExternalResearch")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Outcome");

                    b.HasIndex("StartedAt");

                    b.ToTable("AiPlanningRuns");
                });

            modelBuilder.Entity("Dishhive.Api.Models.Cookbook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Cookbooks");
                });

            modelBuilder.Entity("Dishhive.Api.Models.CookbookEntry", b =>
                {
                    b.Property<Guid>("CookbookId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("CookbookId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("CookbookEntries");
                });

            modelBuilder.Entity("Dishhive.Api.Models.DietaryTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Kind")
                        .IsUnique();

                    b.ToTable("DietaryTags");
                });

            modelBuilder.Entity("Dishhive.Api.Models.FamilyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PreferenceNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsGuest");

                    b.ToTable("FamilyMembers");
                });

            modelBuilder.Entity("Dishhive.Api.Models.FamilyMemberDietaryTag", b =>
                {
                    b.Property<Guid>("FamilyMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DietaryTagId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExcludedClasses")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.HasKey("FamilyMemberId", "DietaryTagId");

                    b.HasIndex("DietaryTagId");

                    b.ToTable("FamilyMemberDietaryTags");
                });

            modelBuilder.Entity("Dishhive.Api.Models.FamilyMemberFavorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DishName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("FamilyMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FamilyMemberId");

                    b.HasIndex("RecipeId");

                    b.ToTable("FamilyMemberFavorites");
                });

            modelBuilder.Entity("Dishhive.Api.Models.MealRating", b =>
                {
                    b.Property<Guid>("PlannedMealId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FamilyMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("PlannedMealId", "FamilyMemberId");

                    b.HasIndex("FamilyMemberId");

                    b.ToTable("MealRatings");
                });

            modelBuilder.Entity("Dishhive.Api.Models.PlannedMeal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Course")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("DishName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("Eaten")
                        .HasColumnType("integer");

                    b.Property<int>("FreezyItemQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("FreezyItemRef")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("MealType")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<string>("SuggestionKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("VagueInstruction")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("DishName");

                    b.HasIndex("RecipeId");

                    b.HasIndex("SuggestionKey")
                        .IsUnique();

                    b.ToTable("PlannedMeals");
                });

            modelBuilder.Entity("Dishhive.Api.Models.PlannedMealAttendee", b =>
                {
                    b.Property<Guid>("PlannedMealId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FamilyMemberId")
                        .HasColumnType("uuid");

                    b.HasKey("PlannedMealId", "FamilyMemberId");

                    b.HasIndex("FamilyMemberId");

                    b.ToTable("PlannedMealAttendees");
                });

            modelBuilder.Entity("Dishhive.Api.Models.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("CookTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("DietaryFactsAssessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DietaryFactsStatus")
                        .HasColumnType("integer");

                    b.Property<string>("ImageContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("bytea");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Keywords")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("PrepTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("Servings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4);

                    b.Property<string>("SourceProvider")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceRawData")
                        .HasColumnType("jsonb");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("TotalTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("SourceUrl")
                        .IsUnique();

                    b.HasIndex("Title");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Dishhive.Api.Models.RecipeDietaryFact", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<int>("IngredientClass")
                        .HasColumnType("integer");

                    b.HasKey("RecipeId", "IngredientClass");

                    b.ToTable("RecipeDietaryFacts");
                });

            modelBuilder.Entity("Dishhive.Api.Models.RecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("OriginalQuantity")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<string>("OriginalText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("OriginalUnit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("Dishhive.Api.Models.RecipeStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeSteps");
                });

            modelBuilder.Entity("Dishhive.Api.Models.RecipeTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RecipeTags");
                });

            modelBuilder.Entity("Dishhive.Api.Models.RecipeTagAssignment", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecipeTagId")
                        .HasColumnType("uuid");

                    b.HasKey("RecipeId", "RecipeTagId");

                    b.HasIndex("RecipeTagId");

                    b.ToTable("RecipeTagAssignments");
                });

            modelBuilder.Entity("Dishhive.Api.Models.UserSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Key");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("Dishhive.Api.Models.CookbookEntry", b =>
                {
                    b.HasOne("Dishhive.Api.Models.Cookbook", "Cookbook")
                        .WithMany("Entries")
                        .HasForeignKey("CookbookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dishhive.Api.Models.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cookbook");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Dishhive.Api.Models.FamilyMemberDietaryTag", b =>
                {
                    b.HasOne("Dishhive.Api.Models.DietaryTag", "DietaryTag")
                        .WithMany("Members")
                        .HasForeignKey("DietaryTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dishhive.Api.Models.FamilyMember", "FamilyMember")
                        .WithMany("DietaryTags")
                        .HasForeignKey("FamilyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DietaryTag");

                    b.Navigation("FamilyMember");
                });

            modelBuilder.Entity("Dishhive.Api.Models.FamilyMemberFavorite", b =>
                {
                    b.HasOne("Dishhive.Api.Models.FamilyMember", "FamilyMember")
                        .WithMany()
                        .HasForeignKey("FamilyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dishhive.Api.Models.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FamilyMember");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Dishhive.Api.Models.MealRating", b =>
                {
                    b.HasOne("Dishhive.Api.Models.FamilyMember", "FamilyMember")
                        .WithMany()
                        .HasForeignKey("FamilyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dishhive.Api.Models.PlannedMeal", "PlannedMeal")
                        .WithMany("Ratings")
                        .HasForeignKey("PlannedMealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FamilyMember");

                    b.Navigation("PlannedMeal");
                });

            modelBuilder.Entity("Dishhive.Api.Models.PlannedMeal", b =>
                {
                    b.HasOne("Dishhive.Api.Models.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Dishhive.Api.Models.PlannedMealAttendee", b =>
                {
                    b.HasOne("Dishhive.Api.Models.FamilyMember", "FamilyMember")
                        .WithMany()
                        .HasForeignKey("FamilyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dishhive.Api.Models.PlannedMeal", "PlannedMeal")
                        .WithMany("Attendees")
                        .HasForeignKey("PlannedMealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FamilyMember");

                    b.Navigation("PlannedMeal");
                });

            modelBuilder.Entity("Dishhive.Api.Models.RecipeDietaryFact", b =>
                {
                    b.HasOne("Dishhive.Api.Models.Recipe", "Recipe")
                        .WithMany("DietaryFacts")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Dishhive.Api.Models.RecipeIngredient", b =>
                {
                    b.HasOne("Dishhive.Api.Models.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Dishhive.Api.Models.RecipeStep", b =>
                {
                    b.HasOne("Dishhive.Api.Models.Recipe", "Recipe")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Dishhive.Api.Models.RecipeTagAssignment", b =>
                {
                    b.HasOne("Dishhive.Api.Models.Recipe", "Recipe")
                        .WithMany("Tags")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dishhive.Api.Models.RecipeTag", "RecipeTag")
                        .WithMany("Recipes")
                        .HasForeignKey("RecipeTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("RecipeTag");
                });

            modelBuilder.Entity("Dishhive.Api.Models.Cookbook", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Dishhive.Api.Models.DietaryTag", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Dishhive.Api.Models.FamilyMember", b =>
                {
                    b.Navigation("DietaryTags");
                });

            modelBuilder.Entity("Dishhive.Api.Models.PlannedMeal", b =>
                {
                    b.Navigation("Attendees");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("Dishhive.Api.Models.Recipe", b =>
                {
                    b.Navigation("DietaryFacts");

                    b.Navigation("Ingredients");

                    b.Navigation("Steps");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Dishhive.Api.Models.RecipeTag", b =>
                {
                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
